### ISSUE TITLE
User Story 18, List of Pets that have applications on them

### ISSUE THREAD

**Issue by ajtran303** [moosehandlr/Adopt_Dont_Shop_Paired#22]
As a visitor
After one or more applications have been created
When I visit the favorites index page
I see a section on the page that has a list of all of the pets that have at least one application on them
Each pet's name is a link to their show page

**Comment by ajtran303** [comment]
For this user story, we should use a `within` block to test for the pet name links.
This is because the favorites index page might already have pet name links in the "favorite index".

**Comment by ajtran303** [comment]
We just implemented an instance method `#change_status` on the Pet model.
Every pet that gets an application will have its status changed to "Pending".
That status gets changed when the application is submitted, so by `applications_controller#create`
Our problem is that we go back to `favorites_controller#index` and at the moment we can't get the `pending_pets` there.

We need to figure out how to get "Pending Pets" into the Favorites Index Page.

**Comment by ajtran303** [comment]
Additionally, we should do a refresher on AR methods: https://docs.google.com/presentation/d/1UjpEzJthDFPlMzqSVzDdmPKznyn5KjaPTI-CJonGvYc/edit#slide=id.p

**Comment by moosehandlr** [comment]
**application_controller.rb#create**
`selected_pets = params.keys.find_all { |key| key.include?("select-") }

    if applications_params.values.any?(&:empty?) || selected_pets.empty?
      flash[:submitted] = "Form must be completed and pets selected in order to submit the application."
      redirect_to "/applications/new"
    else
      selected_pets.each do |pet|
        p = Pet.find(params[pet].to_i)
        p.change_status
        p.save
        favorites.remove_pet(params[pet])
      end
      flash[:submitted] = "Application successfully submitted!"
      redirect_to "/favorites"
    end
  end
`

**Error message:**
`Failures:

  1) Pet favorites spec After one or more applications have been created I see a SECTION with a list of pets that have an application
     Failure/Error: expect(page).to have_link(@doggo.name, href: "/pets/#{@doggo.id}")
       expected to find link "Doggo" with href "/pets/341" but there were no matches
     # ./spec/features/favorites/index_spec.rb:117:in `block (3 levels) in <top (required)>'
`

**Comment by ajtran303** [comment]
I think we have to hit up our join table, pet_applications

**Comment by moosehandlr** [comment]
When an applicant fills out form, that information (name, address etc) is populated on the applications db table.

**Comment by ajtran303** [comment]
We finally did it!
